/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caring_desktop;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models_caring.Service_Model;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.methods.PostMethod;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Panwar
 */
public class Main_Panel extends javax.swing.JFrame {
    
    List<Service_Model> data = new ArrayList<Service_Model>();
    ArrayList<Service_Model> Selected_Services = new ArrayList<Service_Model>();
    ArrayList<String> Selected_Segments = new ArrayList<String>();

    /**
     * Creates new form EntryPanel
     */
    public Main_Panel() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booking_table = new javax.swing.JTable();
        refresh_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        select_tag = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vendor_list = new javax.swing.JTable();
        vendor_search = new javax.swing.JButton();
        vendor_tag = new javax.swing.JTextField();
        vendor_select = new javax.swing.JComboBox<>();
        refresh_vendor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        service_table = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        field_name_service = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        field_code_serve = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        car_model = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        car_year = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        car_segment = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        car_brand = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        car_code = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        car_fuel = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        car_list = new javax.swing.JTable();
        submit_car = new javax.swing.JButton();
        refresh_car = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        field_vendor_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        field_ven_address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        field_price_low = new javax.swing.JTextField();
        field_price_high = new javax.swing.JTextField();
        field_time_open = new javax.swing.JTextField();
        field_time_close = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        field_lat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        field_long = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        field_segment_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        field_des = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        field_assure = new javax.swing.JTextField();
        field_url = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        field_no_img = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        field_id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        field_contact = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ratings = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        label_selected_services = new javax.swing.JLabel();
        label_selected_segment = new javax.swing.JLabel();
        status_serve = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booking_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(booking_table);

        refresh_button.setText("Refresh");
        refresh_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_buttonActionPerformed(evt);
            }
        });

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        select_tag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOOK_ID", "BOOK_USER", "BOOK_VEND_ID", "BOOK_VEND_NAME" }));
        select_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_tagActionPerformed(evt);
            }
        });

        jLabel20.setText("Tag");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh_button)
                .addGap(159, 159, 159))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh_button)
                    .addComponent(search_button)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Bookings", jPanel2);

        vendor_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(vendor_list);

        vendor_search.setText("Search");
        vendor_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_searchActionPerformed(evt);
            }
        });

        vendor_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VEN_NAME", "VEN_ID", "VEN_SERVE", "VEN_SERVE_NAME" }));

        refresh_vendor.setText("Refresh");
        refresh_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_vendorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(vendor_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_tag, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vendor_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh_vendor)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendor_search)
                    .addComponent(vendor_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendor_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh_vendor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Vendor List", jPanel3);

        service_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(service_table);

        jLabel21.setText("Service Name");

        jLabel22.setText("Service Code");

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_name_service, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field_code_serve, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(field_name_service, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(field_code_serve, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service Name", jPanel4);

        jLabel23.setText("CAR MODEL");

        jLabel25.setText("CAR YEAR");

        jLabel26.setText("CAR SEGMENT");

        jLabel27.setText("CAR BRAND");

        jLabel28.setText("CAR CODE");

        jLabel29.setText("CAR FUEL");

        car_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(car_list);

        submit_car.setText("SUBMIT");
        submit_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_carActionPerformed(evt);
            }
        });

        refresh_car.setText("REFRESH");
        refresh_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_carActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(car_model)
                                    .addComponent(car_year)
                                    .addComponent(car_segment, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(car_brand)
                                    .addComponent(car_code)
                                    .addComponent(car_fuel, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(refresh_car, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(submit_car, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 247, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(car_model, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(car_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(car_year, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(car_code, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(car_segment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(car_fuel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit_car, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refresh_car, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cars", jPanel5);

        jLabel1.setText("Vendor Name");

        jLabel2.setText("Vendor Address");

        jLabel5.setText("Price Low");

        jLabel6.setText("Price High");

        jLabel7.setText("Open Timings");

        jLabel8.setText("Close Timings");

        jLabel10.setText("Rating");

        jLabel11.setText("Latitude");

        jLabel12.setText("Longitude");

        jLabel13.setText("Segment Name");

        jLabel14.setText("Description");

        jLabel15.setText("Assurance");

        jLabel16.setText("Url");

        jLabel17.setText("No image");

        jLabel18.setText("Id");

        jLabel19.setText("Contact");

        ratings.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.5", "3", "3.5", "4", "4.5", "5" }));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Select Services");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Select Segment");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        label_selected_services.setText("Selected Services");

        label_selected_segment.setText("Selected Segments");

        status_serve.setText("Status : idle");

        jButton7.setText("Check Internet");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel24.setText("Service details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_selected_services)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(status_serve)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_selected_segment)))
                .addGap(473, 473, 473))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_time_close)
                            .addComponent(field_time_open)
                            .addComponent(field_price_high)
                            .addComponent(field_price_low)
                            .addComponent(field_vendor_name)
                            .addComponent(field_ven_address)
                            .addComponent(ratings, 0, 290, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_contact, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(field_url)
                    .addComponent(field_segment_name)
                    .addComponent(field_des)
                    .addComponent(field_assure)
                    .addComponent(field_no_img)
                    .addComponent(field_id)
                    .addComponent(field_lat)
                    .addComponent(field_long, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_vendor_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1)
                    .addComponent(field_segment_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_ven_address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(field_des, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(field_assure, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_url, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_price_low, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(field_no_img, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_price_high, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(field_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_time_open, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(field_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_time_close, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ratings, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(label_selected_services)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_selected_segment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_serve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_lat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_long, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Enter Vendor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_carActionPerformed
        // TODO add your handling code here:
        String url = "http://www.car-ing.com/app/Get_All_Cars.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            int statusCode = client.executeMethod(method);
            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                Populate_Cars_Data(in);
            }
            System.out.println(""+in);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_refresh_carActionPerformed

    private void submit_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_carActionPerformed
        // TODO add your handling code here:
        String url = "http://www.car-ing.com/app/Insert_Car.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);

            //Add any parameter if u want to send it with Post req.
            method.addParameter("car_model",car_model.getText().toString());
            method.addParameter("car_year",car_year.getText().toString());
            method.addParameter("car_segment",car_segment.getText().toString());
            method.addParameter("car_brand",car_brand.getText().toString());
            method.addParameter("car_code",car_code.getText().toString());
            method.addParameter("car_fuel", car_fuel.getText().toString());

            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                JOptionPane.showMessageDialog(null,"Car Uploaded");

            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_submit_carActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String url = "http://www.car-ing.com/app/Get_Services.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                Populate_Service_Data(in);
            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String url = "http://www.car-ing.com/app/Insert_Service.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            method.addParameter("SERVE_CODE",field_code_serve.getText().toString());
            method.addParameter("SERVE_NAME", field_name_service.getText().toString());
            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                JOptionPane.showMessageDialog(null,"Service Uploaded");

                //Populate_Service_Data(in);
            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void refresh_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_vendorActionPerformed
        // TODO add your handling code here:

        String search_tag = vendor_select.getSelectedItem().toString();
        String url = "http://www.car-ing.com/app/GetAllVendor.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            method.addParameter("tag", vendor_tag.getText().toString());
            method.addParameter("sel", search_tag);
            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                Populate_Search_Vendor_Data(in);

            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_refresh_vendorActionPerformed

    private void vendor_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_searchActionPerformed
        // TODO add your handling code here:
        String search_tag = vendor_select.getSelectedItem().toString();
        String url = "http://www.car-ing.com/app/GetVendorTag.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            method.addParameter("tag", vendor_tag.getText().toString());
            method.addParameter("sel", search_tag);
            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                Populate_Search_Vendor_Data(in);

            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_vendor_searchActionPerformed

    private void select_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_tagActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        String search_tag = select_tag.getSelectedItem().toString();
        String url = "http://www.car-ing.com/app/GetBookingTag.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            method.addParameter("tag", search_field.getText().toString());
            method.addParameter("sel", search_tag);
            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                Populate_Search_Book_Data(in);

            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_search_buttonActionPerformed

    private void refresh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_buttonActionPerformed
        // TODO add your handling code here:

        String search_tag = select_tag.getSelectedItem().toString();
        String url = "http://www.car-ing.com/app/GetAllBooking.php";
        InputStream in = null;
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);
            int statusCode = client.executeMethod(method);
            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                Populate_Search_Book_Data(in);
            }
            System.out.println(""+in);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_refresh_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        field_assure.setText("");
        field_code_serve.setText("");
        field_contact.setText("");
        field_des.setText("");
        field_id.setText("");
        field_lat.setText("");
        field_long.setText("");
        field_name_service.setText("");
        field_no_img.setText("");
        field_price_high.setText("");
        field_price_low.setText("");
       // field_segment_code.setText("");
        field_segment_name.setText("");
       // field_serve_name.setText("");
        //field_service_code.setText("");
        field_time_close.setText("");
        field_time_open.setText("");
        field_url.setText("");
        field_ven_address.setText("");
        field_vendor_name.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        String url = "http://www.car-ing.com/app/Insert_Vendor.php";
        InputStream in = null;
        
        int rows_tot = Selected_Segments.size()*Selected_Services.size();
        
        status_serve.setText(" Status : Total rows "+rows_tot);
        
        
        for(int i=0;i<Selected_Services.size();i++)
        {
        
            for(int j = 0 ; j<Selected_Segments.size();j++)
            {
                
        //jProgressBar1.setMaximum(10);
        try {
            HttpClient client = new HttpClient();
            PostMethod method = new PostMethod(url);

            //Add any parameter if u want to send it with Post req.
            method.addParameter("VEN_ID", field_id.getText().toString());
            method.addParameter("VEN_NAME",field_vendor_name.getText().toString());
            method.addParameter("VEN_ADD",field_ven_address.getText().toString());
            method.addParameter("VEN_LAT",field_lat.getText().toString());
            method.addParameter("VEN_LONG",field_long.getText().toString());
            method.addParameter("VEN_PRICE_LOW",field_price_low.getText().toString());
            method.addParameter("VEN_PRICE_HIGH", field_price_high.getText().toString());
            method.addParameter("VEN_DES",field_des.getText().toString());
            method.addParameter("VEN_OPEN_TIME",field_time_open.getText().toString());
            method.addParameter("VEN_CLOSE_TIME",field_time_close.getText().toString());
            method.addParameter("VEN_RATING",ratings.getSelectedItem().toString());
            method.addParameter("VEN_ASSURE", field_assure.getText().toString());
            method.addParameter("VEN_SERVE",Selected_Services.get(i).getSERVE_CODE());
            method.addParameter("VEN_SEGMENT_CODE",Selected_Segments.get(j));
            method.addParameter("VEN_SEGMENT_NAME", field_segment_name.getText().toString());
            method.addParameter("VEN_SERVE_NAME",Selected_Services.get(i).getSERVE_NAME());
            method.addParameter("VEN_URL", field_url.getText().toString());
            method.addParameter("VEN_NO_IMG", field_no_img.getText().toString());
            method.addParameter("VEN_CONTACT", field_contact.getText().toString());
            // System.out.println(method.getParameters());

            int statusCode = client.executeMethod(method);

            if (statusCode != -1)
            {
                in = method.getResponseBodyAsStream();
                //getJsonObject(in);
                
        status_serve.setText(" Status : Total rows "+rows_tot+" , inserted "+(j*i)+"");
        

            }

            System.out.println(""+in);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
            }
        
        
        
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Service_List servicelist = new Service_List(data, this);
        //servicelist.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public void Set_Label_Service(ArrayList<Service_Model> data)
    {
        Selected_Services.clear();
        Selected_Services = data;
        label_selected_services.setText("Selected Services : "+data.size());
        for(int i=0;i<data.size();i++)
        {
            jLabel24.setText(""+jLabel24.getText()+", "+data.get(i).getSERVE_NAME());
        }
        
    }
    
    public void Set_Label_Segments(ArrayList<String> data)
    {
        Selected_Segments.clear();
        Selected_Segments = data;
        label_selected_segment.setText("Selected Segments"+data.size());
        
    }
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        Select_Segment select_Segment = new Select_Segment(this);
        
               
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //private static boolean netIsAvailable() 
    try {
        final URL url = new URL("http://www.google.com");
        final URLConnection conn = url.openConnection();
        conn.connect();
        System.out.println("connected");
        JOptionPane.showMessageDialog(null, "connected", "Alert", JOptionPane.OK_OPTION);        

        //return true;
    } catch (MalformedURLException e) {
        throw new RuntimeException(e);
    } catch (IOException e) {
        
        System.out.println("not connected");
        
        JOptionPane.showMessageDialog(null, "Not connected", "Alert", JOptionPane.ERROR_MESSAGE);
        //return false;
    }

    }//GEN-LAST:event_jButton7ActionPerformed

    public void Populate_Vendor_List()
    {
    }
    
    
      public void Populate_Search_Vendor_Data(InputStream inputStream)
    {
        
        
        JSONObject jsonobject = new JSONObject();
        try {
            jsonobject = getJsonObject(inputStream);
        } catch (JSONException ex) {
             //JOptionPane.showMessageDialog(null,"No Records Returned");
            
               Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
               return;
          
        }
        
         DefaultTableModel model = new DefaultTableModel();
         Object[] columnsName = new Object[20];
        
        columnsName[0] = "VEN_ID";
        columnsName[1] = "VEN_NAME";
        columnsName[2] = "VEN_DES";
        columnsName[3] = "VEN_ASSURE";
        columnsName[4] = "VEN_URL";
        columnsName[5] = "VEN_NO_IMG";
        columnsName[6] = "VEN_SERVE";
        columnsName[7] = "VEN_PRICE_LOW";
        columnsName[8] = "VEN_PRICE_HIGH";
        columnsName[9] = "VEN_TIME_OPEN";
        columnsName[10] = "VEN_TIME_CLOSE";
        columnsName[11] = "VEN_SEGMENT";
        columnsName[12] = "VEN_RATING";
        columnsName[13] = "VEN_LAT";
        columnsName[14] = "VEN_LONG";
        columnsName[15] = "VEN_SERVE_NAME";
        columnsName[16] = "VEN_SEGMENT_NAME";
        columnsName[17] = "VEN_ADDRESS";
        columnsName[18] = "VEN_CONTACT";
        
        model.setColumnIdentifiers(columnsName);
        Object[] rowData = new Object[19];
                  try {   
            JSONArray jsonarray = jsonobject.getJSONArray("Vendor_Data");
            System.out.println("json length "+jsonarray.length());
            for(int i=0;i<jsonarray.length();i++)
            {
                JSONObject temp_obj = jsonarray.getJSONObject(i);
                rowData[0] = temp_obj.get("VEN_ID");
                rowData[1] = temp_obj.get("VEN_NAME");
                rowData[2] = temp_obj.get("VEN_DES");
                rowData[3] = temp_obj.get("VEN_ASSURE");
                rowData[4] = temp_obj.get("VEN_URL");
                rowData[5] = temp_obj.get("VEN_NO_IMG");
                rowData[6] = temp_obj.get("VEN_SERVE");
                rowData[7] = temp_obj.get("VEN_PRICE_LOW");
                rowData[8] = temp_obj.get("VEN_PRICE_HIGH");
                rowData[9] = temp_obj.get("VEN_TIME_OPEN");
                rowData[10] = temp_obj.get("VEN_TIME_CLOSE");
                rowData[11] = temp_obj.get("VEN_SEGMENT");
                rowData[12] = temp_obj.get("VEN_RATING");
                rowData[13] = temp_obj.get("VEN_LAT");
                rowData[14] = temp_obj.get("VEN_LONG");
                rowData[15] = temp_obj.get("VEN_SERVE_NAME");
                rowData[16] = temp_obj.get("VEN_SEGMENT_NAME");
                rowData[17] = temp_obj.get("VEN_ADDRESS");
                rowData[18] = temp_obj.get("VEN_CONTACT");
                
                 model.addRow(rowData);
                
            }
            
            vendor_list.setModel(model);
            
            
        } catch (JSONException ex) {
            Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
     public void Populate_Service_Data(InputStream inputStream)
    {
        
        
        JSONObject jsonobject = new JSONObject();
        try {
            jsonobject = getJsonObject(inputStream);
        } catch (JSONException ex) {
             //JOptionPane.showMessageDialog(null,"No Records Returned");
            
               Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
               return;
          
        }
        
         DefaultTableModel model = new DefaultTableModel();
         Object[] columnsName = new Object[3];
        
        columnsName[0] = "SERVE_ID";
        columnsName[1] = "SERVE_CODE";
        columnsName[2] = "SERVE_NAME";
       
        
        model.setColumnIdentifiers(columnsName);
        Object[] rowData = new Object[3];
                  try {   
            JSONArray jsonarray = jsonobject.getJSONArray("Services");
            System.out.println("json length "+jsonarray.length());
            for(int i=0;i<jsonarray.length();i++)
            {
                JSONObject temp_obj = jsonarray.getJSONObject(i);
                Service_Model service_model = new Service_Model();
                rowData[0] = temp_obj.get("SERVE_SN");
                rowData[1] = temp_obj.get("SERVE_CODE");
                rowData[2] = temp_obj.get("SERVE_NAME");
                service_model.setSERVE_CODE(temp_obj.getString("SERVE_CODE"));
                service_model.setSERVE_NAME(temp_obj.getString("SERVE_NAME"));
                 model.addRow(rowData);
                 data.add(service_model);
                
            }
            
            service_table.setModel(model);
            
            
        } catch (JSONException ex) {
            Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    private JSONObject getJsonObject(InputStream inputStreamObject) throws JSONException
    {

    //Create input stream
    JSONObject jsonObject = null;
   try {
       BufferedReader streamReader = new BufferedReader(new InputStreamReader(inputStreamObject, "UTF-8"));
       StringBuilder responseStrBuilder = new StringBuilder();

       String inputStr;
       while ((inputStr = streamReader.readLine()) != null)
       {
           responseStrBuilder.append(inputStr);
       }
       jsonObject = new JSONObject(responseStrBuilder.toString());
       System.out.print(""+jsonObject.toString());
   }
   catch (IOException e) 
   {
        JOptionPane.showMessageDialog(null,"No Records Returned");
            
       e.printStackTrace();
   }

    //if something went wrong, return null
    return jsonObject;
}
    
    
    
    public void Populate_Search_Book_Data(InputStream inputStream)
    {
        
        
        JSONObject jsonobject = new JSONObject();
        try {
            jsonobject = getJsonObject(inputStream);
        } catch (JSONException ex) {
             //JOptionPane.showMessageDialog(null,"No Records Returned");
            
               Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
               return;
          
        }
        
         DefaultTableModel model = new DefaultTableModel();
         Object[] columnsName = new Object[18];
        
        columnsName[0] = "BOOK_USER";
        columnsName[1] = "BOOK_ID";
        columnsName[2] = "BOOK_DES";
        columnsName[3] = "BOOK_CAR_NAME";
        columnsName[4] = "BOOK_CAR_CODE";
        columnsName[5] = "BOOK_VEND_ID";
        columnsName[6] = "BOOK_VEND_NAME";
        columnsName[7] = "BOOK_PRICE";
        columnsName[8] = "BOOK_ADDRESS";
        columnsName[9] = "BOOK_DATE";
        columnsName[10] = "BOOK_PAYID";
        columnsName[11] = "BOOK_STATUS";
        columnsName[12] = "BOOK_START_TIME";
        columnsName[13] = "BOOK_LAT";
        columnsName[14] = "BOOK_LONG";
        columnsName[15] = "BOOK_ADVANCE";
        columnsName[16] = "BOOK_DISCOUNT";
        columnsName[17] = "BOOK_TAXES";
        
        model.setColumnIdentifiers(columnsName);
        Object[] rowData = new Object[18];
                  try {   
            JSONArray jsonarray = jsonobject.getJSONArray("Book_Data");
            System.out.println("json length "+jsonarray.length());
            for(int i=0;i<jsonarray.length();i++)
            {
                JSONObject temp_obj = jsonarray.getJSONObject(i);
                rowData[0] = temp_obj.get("BOOK_USER");
                rowData[1] = temp_obj.get("BOOK_ID");
                rowData[2] = temp_obj.get("BOOK_DES");
                rowData[3] = temp_obj.get("BOOK_CAR_NAME");
                rowData[4] = temp_obj.get("BOOK_CAR_CODE");
                rowData[5] = temp_obj.get("BOOK_VEND_ID");
                rowData[6] = temp_obj.get("BOOK_VEND_NAME");
                rowData[7] = temp_obj.get("BOOK_PRICE");
                rowData[8] = temp_obj.get("BOOK_ADDRESS");
                rowData[9] = temp_obj.get("BOOK_DATE");
                rowData[10] = temp_obj.get("BOOK_PAYID");
                rowData[11] = temp_obj.get("BOOK_STATUS");
                rowData[12] = temp_obj.get("BOOK_START_TIME");
                rowData[13] = temp_obj.get("BOOK_LAT");
                rowData[14] = temp_obj.get("BOOK_LONG");
                rowData[15] = temp_obj.get("BOOK_ADVANCE");
                rowData[16] = temp_obj.get("BOOK_DISCOUNT");
                rowData[17] = temp_obj.get("BOOK_TAXES");
                 model.addRow(rowData);
                
            }
            
            booking_table.setModel(model);
            
            
        } catch (JSONException ex) {
            Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void Populate_Cars_Data(InputStream inputStream)
    {
        
        
        JSONObject jsonobject = new JSONObject();
        try {
            jsonobject = getJsonObject(inputStream);
        } catch (JSONException ex) {
             //JOptionPane.showMessageDialog(null,"No Records Returned");
            
               Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
               return;
          
        }
        
         DefaultTableModel model = new DefaultTableModel();
         Object[] columnsName = new Object[7];
        
        columnsName[0] = "CAR_ID";
        columnsName[1] = "CAR_CODE";
        columnsName[2] = "CAR_MODEL";
        columnsName[3] = "CAR_BRAND";
        columnsName[4] = "CAR_YEAR";
        columnsName[5] = "CAR_FUEL";
        columnsName[6] = "CAR_CODE";        
        model.setColumnIdentifiers(columnsName);
        Object[] rowData = new Object[7];
                  try {   
            JSONArray jsonarray = jsonobject.getJSONArray("User_Car");
            System.out.println("json length "+jsonarray.length());
            for(int i=0;i<jsonarray.length();i++)
            {
                JSONObject temp_obj = jsonarray.getJSONObject(i);
                rowData[0] = temp_obj.get("CAR_ID");
                rowData[1] = temp_obj.get("CAR_CODE");
                rowData[2] = temp_obj.get("CAR_MODEL");
                rowData[3] = temp_obj.get("CAR_BRAND");
                rowData[4] = temp_obj.get("CAR_YEAR");
                rowData[5] = temp_obj.get("CAR_FUEL");
                rowData[6] = temp_obj.get("CAR_CODE");
                 model.addRow(rowData);
                
            }
            
            car_list.setModel(model);
            
            
        } catch (JSONException ex) {
            Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booking_table;
    private javax.swing.JTextField car_brand;
    private javax.swing.JTextField car_code;
    private javax.swing.JTextField car_fuel;
    private javax.swing.JTable car_list;
    private javax.swing.JTextField car_model;
    private javax.swing.JTextField car_segment;
    private javax.swing.JTextField car_year;
    private javax.swing.JTextField field_assure;
    private javax.swing.JTextField field_code_serve;
    private javax.swing.JTextField field_contact;
    private javax.swing.JTextField field_des;
    private javax.swing.JTextField field_id;
    private javax.swing.JTextField field_lat;
    private javax.swing.JTextField field_long;
    private javax.swing.JTextField field_name_service;
    private javax.swing.JTextField field_no_img;
    private javax.swing.JTextField field_price_high;
    private javax.swing.JTextField field_price_low;
    private javax.swing.JTextField field_segment_name;
    private javax.swing.JTextField field_time_close;
    private javax.swing.JTextField field_time_open;
    private javax.swing.JTextField field_url;
    private javax.swing.JTextField field_ven_address;
    private javax.swing.JTextField field_vendor_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_selected_segment;
    private javax.swing.JLabel label_selected_services;
    private javax.swing.JComboBox<String> ratings;
    private javax.swing.JButton refresh_button;
    private javax.swing.JButton refresh_car;
    private javax.swing.JButton refresh_vendor;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JComboBox<String> select_tag;
    private javax.swing.JTable service_table;
    private javax.swing.JLabel status_serve;
    private javax.swing.JButton submit_car;
    private javax.swing.JTable vendor_list;
    private javax.swing.JButton vendor_search;
    private javax.swing.JComboBox<String> vendor_select;
    private javax.swing.JTextField vendor_tag;
    // End of variables declaration//GEN-END:variables
}
